### PR TITLE
Cluster on WAS commits from 0.7x + adding testing coverage on it

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ederign** [comment]
@psiroky how can I retrigger the build?

**Comment by psiroky** [comment]
@ederign by commenting "jenkins retest this" (no need right now as I just did it)

**Comment by csadilek** [comment]
Thanks.

master: 1d61889e90f498a42cfa3ac1f6115b0671c023a2 652ebcb0cbe2490be1e9de7b6e05708e919108cb

**Pull request closed without merging**
