### PR TITLE
Fix transient dependencies

### PR DESCRIPTION
**Pull request by manstis**
@mbiarnes Hi, could you please review (to fix master build on Jenkins)?

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
+1

**Comment by manstis** [comment]
Build failure is unrelated to this PR... both @mbiarnes and myself have built successfully locally.

**Comment by yurloc** [comment]
s/transient/transitive/ :smile:

**Pull request merged**
