### PR TITLE
[Urgent] BZ-1266138: managed beans can't be used during container lifecycle on WAS.

### PR DESCRIPTION
**Pull request by porcelli**
BZ-1266138: managed beans can't be used during container lifecycle on WAS. Code is not nice, but is the only way that I managed to make it work on WAS without changing all architecture.

Important note: this "code" is the only way to make it work on WAS that i found.

### CODE REVIEW

**Comment by ederign** [comment]
for reviewers: I'll write the required tests for this PR tomorrow in other PR.

**Comment by ederign** [comment]
+1

**Comment by porcelli** [comment]
@ederign any tests here will be just to test what's impossible to test ;) - to test it properly we'd need WAS on CI and execute a smoke test. But feel free to test what's `ridiculous`

**Comment by ederign** [comment]
@porcelli IMO we should guarantee that "unused" stuff like:

     @Inject
     @Named("configIO")
     private IOService ioService;

will not be removed in the future. (specially because IDE's will mark it as not used code)

**Comment by manstis** [comment]
There's some crazy shot going on here... +1 to merge (in my ignorance)

**Comment by porcelli** [comment]
@ederign only way to do it is using reflection to get the annotation... but this would go beyond the absurd that I could push today :D

**Comment by ederign** [comment]
@porcelli totally agree. if @manstis  and @csadilek dont mind, please merge it and I'll write the tests tomorrow (due to the importance of this fix)

**Comment by csadilek** [comment]
+1 see my comment on https://github.com/uberfire/uberfire/pull/231

**Comment by csadilek** [comment]
thanks.

6.3.x: 17bcc2019582cc7e0a3454539abd51088e59c1c6

**Pull request closed without merging**
