### PR TITLE
add message to thrown exception

### PR DESCRIPTION
**Pull request by zkrejcov**
See also https://github.com/droolsjbpm/drools-wb/pull/162

Philosophy corner:
Do we really need two almost identical implementations of SocialRouter...?

### CODE REVIEW

**Comment by manstis** [comment]
@ederign Could you please review.

**Comment by zkrejcov** [comment]
Check fails due to compilation failure somewhere in jbpm - I do believe this is not related...

**Comment by zkrejcov** [comment]
jenkins retest this

**Comment by ederign** [comment]
+1 @zkrejcov  thanks!
About SocialRouter, is a leftover. I'll clean up that next time that I touch that codebase. Thanks!

**Comment by porcelli** [comment]
+1

**Pull request merged**
