### PR TITLE
Remove showcase

### PR DESCRIPTION
**Pull request by psiroky**
Showcase was used in initial pfly migration and should not be needed anymore (same as for kie-wb-common-showcase which was recently removed).

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge from me, but @ederign @porcelli what are your opinions (IMO it was a nicety to have during the migration to BS3 - same as we had for kie-wb-common).

**Comment by porcelli** [comment]
+1

**Comment by ederign** [comment]
Why delete that? I used it yesterday to fix some simple social issues without having to run kie-wb.

**Comment by ederign** [comment]
Anyway, If there is a maintenance concern you have my +1.

**Comment by psiroky** [comment]
Disclaimer: This is my (build-guy oriented) view.

In this case it is not just the maintenance cost (even though that is I think enough reason most of the times). This repository contains very small number of modules, basically just the (temporary?) taglib and the social activities. So we currently have separate showcase for single set of modules (api, server, client). This dramatically increases the build time. With the showcase enabled, the build of this repository takes four times longer (just quickly measured it on my local machine). It is just few minutes in this case (as the showcase is quite small). However, if we would have showcase in every of our ~15 workbench repositories, the total build time of those showcases only, could easily go to tens of minutes. I believe we need to strive for faster builds, otherwise it gets hard (aka takes too long) to test stuff after doing changes.

**Comment by porcelli** [comment]
@psiroky devil's advocate now:
What if someone makes a mistake and uses on client side a server side only class... without these small showcase's spread around we'll realize that we have such issue just in the end of the journey (kie-wb-distro). What will force us to re-build all stack again.

btw: i'm in favor to remove it, as the complex of showcase still too high to mantain.

**Comment by psiroky** [comment]
@porcelli yes, this is all about trade-offs. I am not saying we should have just the kie-wb, inter-mediate showcases (guvnor, drools-wb, designer, console-ng, optaplanner-wb) may be very useful as well. Just to wanted to point out that having showcase for very small number of modules is not ideal.

**Comment by porcelli** [comment]
@psiroky sure. with that said.. let's remove this.

**Comment by psiroky** [comment]
Great, thanks. I merged the changes into master.

**Pull request merged**
