### PR TITLE
RHBPMS-857 - Fix missing i18n

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@ederign :)

**Comment by ederign** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
@cristianonicolai @ederign I was fixing some bundles in this project, and I am preparing a PR with this and more fixes. Would you mind if we do not merge this PR to make my life easier? :)

**Comment by paulovmr** [comment]
These changes were included here: https://github.com/droolsjbpm/kie-uberfire-extensions/pull/33/files

**Comment by cristianonicolai** [comment]
@paulovmr sure, no problem at all, thanks for looking into this.

**Pull request closed without merging**
